const fs = require('fs');
const path = require('path');

const PLUGIN_DIR = __dirname;
const SRC_DIR = path.join(PLUGIN_DIR, 'src');
const OUTPUT_FILE = path.join(PLUGIN_DIR, 'index.js');

const MODULE_FILES = [
  'core/reflection.js',
  'core/turnStore.js',
  'features/timeline/health.js',
  'features/timeline/rail.js',
  'features/timeline/etaLedger.js',
  'features/timeline/cockpit.js',
  'features/extractor/exporter.js',
  'features/extractor/modal.js',
  'features/cards/cardStore.js',
  'features/cards/cardPopover.js',
  'main.js'
];

function build() {
  console.log('[Timeslip Build] Compiling modular src into index.js...');
  const chunks = [];

  chunks.push('// Generated by build.js - DO NOT EDIT DIRECTLY. Edit modules in src/');
  chunks.push('(function () {');
  chunks.push('  "use strict";\n');

  for (const relPath of MODULE_FILES) {
    const fullPath = path.join(SRC_DIR, relPath);
    if (!fs.existsSync(fullPath)) {
      console.error(`[Timeslip Build Error] File missing: ${fullPath}`);
      process.exit(1);
    }
    const content = fs.readFileSync(fullPath, 'utf-8');
    chunks.push(`  // ==========================================================================`);
    chunks.push(`  // Module: ${relPath}`);
    chunks.push(`  // ==========================================================================\n`);
    chunks.push(content);
    chunks.push('\n');
  }

  chunks.push('})();\n');

  const bundle = chunks.join('\n');
  fs.writeFileSync(OUTPUT_FILE, bundle, 'utf-8');
  console.log(`[Timeslip Build] Successfully generated index.js (${(bundle.length / 1024).toFixed(1)} KB)`);
}

if (require.main === module) {
  build();
}

module.exports = { build };
